export const GET_PHOTOS= 'GET_PHOTOS';
export const GET_PHOTOS_SUCCESS = "GET_PHOTOS_SUCCESS";
export const GET_PHOTOS_FAIL = "GET_PHOTOS_FAIL";

export const GET_MORE_PHOTOS= 'GET_MORE_PHOTOS';
export const GET_MORE_PHOTOS_SUCCESS = "GET_MORE_PHOTOS_SUCCESS";
export const GET_MORE_PHOTOS_FAIL = "GET_MORE_PHOTOS_FAIL";

export const GET_PHOTO_DETAILS= 'GET_PHOTO_DETAILS';
export const GET_PHOTO_DETAILS_SUCCESS = "GET_PHOTO_DETAILS_SUCCESS";
export const GET_PHOTO_DETAILS_FAIL = "GET_PHOTO_DETAILS_FAIL";

export const SET_CURRENT_PAGE= 'SET_CURRENT_PAGE';
export const SET_CURRENT_SEARCH_KEYWORD= 'SET_CURRENT_SEARCH_KEYWORD';
